name: Run Dashboard Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: cs3030
          environment-file: environment.yml
          python-version: 3.11
          auto-activate-base: false
      - name: Verify Environment
        run: |
          conda list
          which python
          python --version
      - name: Run Tests
        run: pytest -v